### ISSUE TITLE
GTX 1660 TI doesn't work with the Miner application

### ISSUE THREAD

**Issue by cryptobench** [Thorg-Dev/ya-provider-winui#181]
Discord user SpM_R3[SIST]#0100 [reports](https://discord.com/channels/684703559954333727/877848913753821225/881946215095336991) that his 1660 TI can't be used to mine in the Miner application. It says GPU support disabled. Antivirus has been tried disabled, but no change.
![image](https://user-images.githubusercontent.com/33448819/132228809-05733018-91c7-42b5-b2e8-67c22fddf1ab.png)

**Comment by scx1332** [comment]
Card is working. There was an issue with DNS or connection to chessongolem.com
