### ISSUE TITLE
better ya-provider error reporting

### ISSUE THREAD

**Issue by warburg-pb** [Thorg-Dev/ya-provider-winui#226]
if provider app crashes or returns with code other than 0 Thorg app should intercept it and raport to sentry (if raporting enabled)

**Comment by prekucki** [comment]
## Test scenarios

### T1: Positive

* start mining 
* node starts mine
* in logs should be info about positive start

### T2: Invalid configuration 

* provider configuration file is corrupted.
* node starts mining
* provider panics with error message.
* in sentry logs there should be info about fail.

### T3: Invalid binary

* exe file have invalid depen
